### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by m1ga**
increase version number for release

### CODE REVIEW

**Review by cb1kenobi — APPROVED** [review]
LGTM! **APPROVED**!

**Comment by m1ga** [comment]
@cb1kenobi Thanks :+1: Could you trigger a release build for this one please so I can add it here https://github.com/tidev/titanium-docs/blob/main/package.json#L37

**Comment by cb1kenobi** [comment]
@m1ga no can do. The release/publish workflow does not support monorepos and thus the `publish.yml` should be removed.

The theme package will need to manually published by I/@ewanharris.

**Comment by ewanharris** [comment]
I can publish it, will ping here when I have

**Comment by ewanharris** [comment]
Published as 4.11.0 (lerna did magic and chose the version number)

**Comment by cb1kenobi** [comment]
Thanks @ewanharris!

**Pull request merged**
